### ISSUE TITLE
Purpose of this fork?

### ISSUE THREAD

**Issue by gravyboat** [livecli/livecli#2]
@back-to Is there any specific reasoning behind this fork?

**Comment by back-to** [comment]
it's easier to change the base code in a fork than in some upstream branches,
side loading a plugin is sometimes just not good enough.

**Comment by gravyboat** [comment]
Gotcha, are you still planning on contributing to Streamlink or are you only going to be updating this one from now on?

**Comment by karlo2105** [comment]
@back-to 
I hope you will keep on your contribution to streamlink because together project is better. Fragmentation is always a loss. Thanks again for your quick reactive response.

**Comment by back-to** [comment]
it depends on which issue.
