### ISSUE TITLE
about pixiv live

### ISSUE THREAD

**Issue by hatabbich** [livecli/livecli#22]
Sorry bro, im not so good at english language, so..
thx for your help, i'm successfully grabbed stream from pixiv.. last quastion, there is no possible grab
video not by profile url, but video url? for exmp blob:https://sketch.pixiv.net/db289dda-64ab-4c5a-8157-166ef9e18dc9?? Ty one more time

**Comment by back-to** [comment]
I don't know were you find such url's

the only url that i see are

`https://sketch.pixiv.net/@name/lives/123123123123`

**Comment by hatabbich** [comment]
well, you can get this url if you click right button on on video, and click copy video adress
Im grabbed by this method picarto stream in vlc, but it's not working with pixiv as i see

**Comment by back-to** [comment]
co-hosts are **already supported** by `livecli`

just use the quality name with the CO-HOST ID

if you don't know the id just run it first without it and you will see the quality names

```
$ livecli https://sketch.pixiv.net/@name/lives/123123123123 270p_22222222
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@name/lives/123123123123
[plugin.pixiv][info] Owner ID: 123123123123
[plugin.pixiv][info] CO-HOST ID: 22222222
[cli][info] Available streams: 270p_22222222, 1080p_22222222, 270p (worst), 1080p (best)
[cli][info] Opening stream: 270p_22222222 (hls)
```

use the browser url,

the right click video url won't work.
