### ISSUE TITLE
Streaming "closing", and need to rejoin manual

### ISSUE THREAD

**Issue by hatabbich** [livecli/livecli#25]
Hi, i have a quastion 2 quastion about some for reliable works
### Description
1. sometimes, livecli ending streaming as if it's ending, but can i add some command in config, that's will be changed it, im talking about Pixiv streaming grab in global.

Expected / Actual behavior
after streaming "probably" ended, livecli tryind to reconnect again, for 3-or 5 times (counts depend on config setting)
/
fake closed ending stream

and 2. Hello, can you please help me
my goal is:

Save all downloads to a custom path: "E:\StreamLink" not in Default video folder

Automatically generate filename for new downloads, at the new download path.

im trying use this command complex in console (windows) , but its not work T_T

C:\Users\bugaku121>livecli https://sketch.pixiv.net/@luciahreat/lives/5917595670370
129833 best -o 1234141.flv --download-dir S:/Recording Livecli/

My bottom part of config file
.........................
# =Number of threads to use when streaming HDS streams
#=hds-segment-threads=1
player="C:\my_app\data app\sys app\vlc1\VLC\vlc.exe"
player-continuous-http
player-no-close
hls-timeout=120 (trying to recconect time??)
auto-output-time (this command give a autoname to file of recording data???)
download-dir S:/Livecli Record/ (i need to save -o record in this folder)
 Update: trying this, and nothing too T_T

C:\Users\bugaku101>livecli https://sketch.pixiv.net/@kokabu777/lives/37971307631403
9426 -ao
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@kokabu
777/lives/379713076314039426
[plugin.pixiv][info] Owner ID: 30274662
[cli][info] Available streams: 270p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Download path: ""S:/Rec/"\https___sketch.pixiv.net_@kokabu777_lives_
379713076314039426.ts"
error: Failed to open output: "S:/Rec/"\https___sketch.pixiv.net_@kokabu777_live
s_379713076314039426.ts ([Errno 22] Invalid argument: '"S:/Rec/"\\https___sketch
.pixiv.net_@kokabu777_lives_379713076314039426.ts')
[cli][info] Closing currently open stream...

**Comment by back-to** [comment]
> reconnect again, for 3-or 5 times

no **livecli can't do this** and i am not planning to add it.

there is only a command if an url expires `--hls-session-reload HH:MM:SS`
but it will only work if the stream is still online

https://livecli.github.io/cli.html#cmdoption-hls-session-reload

---

> --download-dir

it works only for `-ao` or `--auto-output`
https://livecli.github.io/cli.html#cmdoption-ao

if you use `-o`

you will have to add the path to `-o`

```
livecli URL best -o "S:\Recording Livecli\1234141.ts"
```

if you use spaces in your path you need to use quotes like this

---

#### your config

> auto-output-time

this works only with `-ao`

> hls-timeout

this is used for when the connection is slow,
not for a reconnect of an offline stream.

> download-dir

make sure it's a valid path, windows uses `\` not `/`,
but -o won't save it there see above.

**Comment by hatabbich** [comment]
Thank you very much for answer, im 0 in codding and other programmists stuff so.. im using AHK for more automatisation, and now all works fine :)
One more thank you for your help, and wonderful program :smiley:
