### ISSUE TITLE
FC2 error

### ISSUE THREAD

**Issue by hatabbich** [livecli/livecli#26]
can't grab  from fc2.live

C:\Users\Minotaur1201>livecli https://live.fc2.com/83789692/ best
[cli][info] Found matching plugin resolve for URL https://live.fc2.com/83789692/

[plugin.resolve][info] Found iframes: https://live.fc2.com/83789692/<%- val.thum
bUrl %>
error: Unable to open URL: https://live.fc2.com/83789692/<%- val.thumbUrl %> (40
0 Client Error: Bad Request for url: https://live.fc2.com/83789692/%3C%-%20val.t
humbUrl%20%%3E)

**Comment by back-to** [comment]
There is **no plugin** for this website.

---

I tested the website and I **can't get a working m3u8** file from it,
the file that I get is dead until a **websocket** activation.

But I could not find the correct websocket commands.

---

Closing for now,
until someone finds the corrent _websocket commands_ or
the _website changes_.

**Comment by johnthecracker** [comment]
@back-to,

Is it ok if I provide alternative and simple solution ?

This is rtmp stream, rtmpdumphelper + rtmpsuck

RTMP Proxy Server v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu; license: GPL

Streaming on rtmp://0.0.0.0:1935
WARNING: Trying different position for client digest!
Processing connect
       app : live?media_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2ZXIiOiJtZWRpYTEwOTAubGl2ZS5mYzIiLCJjaGFubmVsX2lkIjoiMzM0Mzc5MDYiLCJ1c2VyX2lkIjoiM3N1b3FpdTEwMHAxZnRzNTIycWFsdm5xYzQiLCJjbGllbnRfaWQiOjM1MzYsImNsaWVudF9hcHAiOiJicm93c2VyIiwibW9kZSI6InBsYXkiLCJleHAiOjE1MjUxOTI3MDF9.hnBsem2h0z6qJLmWRmJcgPiLdg-DZrIPFGj_fbD8hL4
  flashVer : WIN 29,0,0,140
    swfUrl : https://live.fc2.com/swf/liveVideo.swf?t=0.9290397252106976
     tcUrl : rtmp://media1090-g.live.fc2.com/live?media_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2ZXIiOiJtZWRpYTEwOTAubGl2ZS5mYzIiLCJjaGFubmVsX2lkIjoiMzM0Mzc5MDYiLCJ1c2VyX2lkIjoiM3N1b3FpdTEwMHAxZnRzNTIycWFsdm5xYzQiLCJjbGllbnRfaWQiOjM1MzYsImNsaWVudF9hcHAiOiJicm93c2VyIiwibW9kZSI6InBsYXkiLCJleHAiOjE1MjUxOTI3MDF9.hnBsem2h0z6qJLmWRmJcgPiLdg-DZrIPFGj_fbD8hL4
   pageUrl : https://live.fc2.com/33437906/
      live : yes
  Playpath : 33437906_rtmp
 Saving as : 2018-05-01_05-37-44_33437906_rtmp.flv
INFO: Metadata:
INFO:   width                   640.00
INFO:   height                  480.00
WARNING: ignoring too small audio packet: size: 0
