### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by longsack** [livecli/livecli#27]
This is not so much an issue as it is i have never used command line programs, and I'm trying this for the 1st time....  I'm unable to get it to work as it should.... as I'm getting error messages.

For example, how would I set the following command line, if you would be so kind as to provide it? https://live.fc2.com/24445130/
username is: jack@jack.com   (example)
password is: jack@jack.com   (example)
And I would like to have it save, not play in a player?

Any thoughts?

I have tried a number of different ways but get errors 
livecli --url https://live.fc2.com/24445130/
[cli][info] Found matching plugin resolve for URL https://live.fc2.com/24445130/
[plugin.resolve][info] Found iframes: https://live.fc2.com/24445130/<%- val.thumbUrl %>
error: Unable to open URL: https://live.fc2.com/24445130/<%- val.thumbUrl %> (400 Client Error: Bad Request for url: https://live.fc2.com/24445130/%3C%-%20val.thumbUrl%20%%3E)

livecli --fc2-username-jack@jack.com --fc2-password-Jacks@jack.com https://live.fc2.com/24445130/
livecli: error: unrecognized arguments: --fc2-username-jack@jack.com --fc2-password-Jacks@jack.com

and them are just trying to get it to play...

Any assistance would be great, thanks so much for the great script!

**Comment by back-to** [comment]
it only works with the **developer version** from github

I will make a new **release version later today**,
it should work then.

**Comment by back-to** [comment]
It should now work with version 3.9.0

https://github.com/livecli/livecli/releases/tag/3.9.0
https://pypi.org/project/livecli/

---

if you want to save the stream locally

use commands from https://livecli.github.io/cli.html#file-output-options
