### ISSUE TITLE
Not An Issue, Perhaps Some Help Anyone

### ISSUE THREAD

**Issue by longsack** [livecli/livecli#31]
First again, thank you for this script... works great....

What i'm trying to do is on fc2 monitor specific live video feeds.  If the channel is on, it will save the video, type of thing.

So I created a .sh script that looks like bellow:
#!/bin/bash

# fc2 Files
livecli --fc2-username user --fc2-password pass https://live.fc2.com/123456/ best -ao --auto-output-only-id --auto-output-time --download-dir /path/path/path/just_recorded &
livecli --fc2-username user --fc2-password pass https://live.fc2.com/123456/ best -ao --auto-output-only-id --auto-output-time --download-dir /path/path/path/just_recorded &
............

Running with the following cronjob:
*/30 * * * * bash /path/path/path/livecli_recorder.sh > /path/path/path/livecli_recorder.log 2>&1

However I get the following error in my log

[cli][info] Opening stream: live (rtmp)
[cli][info] Download path: "/path/path/path/just_recorded
/68216538_2018_05_09_14h55m06s.flv"
error: Failed to open output: /path/path/path/just_recorded
/123456_2018_05_09_14h55m06s.flv ([Errno 2] No such file or directory: '/path/path/path/just_recorded\r/1234568_2018_05_09_14h55m06s.flv')
[cli][info] Closing currently open stream...

Any idea how I could fix this?

**Comment by back-to** [comment]
you added a `\r` in your script / command for the download path

try to use the command with `"`

`--download-dir "/path/path"`

**Comment by longsack** [comment]
So, you got me to thinking.....  I wasn't adding \r to the script... so what would?  Windows?  Used dos2unix, removed the line return, and boom... working like a champ....   Your awesome, thanks so much!
