### ISSUE TITLE
Picarto.tv doesn't work anymore

### ISSUE THREAD

**Issue by hatabbich** [livecli/livecli#33]
### Description

Picarto.tv doesn't grab url anymore

### Expected / Actual behavior

Starting streaming, but gives error 

### Reproduction steps / Explicit  URLs  

**1.**[C:\TCMD20]livecli https://picarto.tv/MarmarsHentaiDungeon best
[cli][info] Found matching plugin picarto for URL https://picarto.tv/MarmarsHentaiDungeon
error: **Expecting value:  1 column 1 (char 0)**

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://livecli.github.io/cli.html#cmdoption-l)
Make sure  **remove username and password**
You can upload your logs  https://gist.github.com/ or_

**Comment by back-to** [comment]
The **stream is offline**, but the **website** says it's **online**.

It's some **issue on there website**

I can't really do anything about it.

---

Livecli will time out the connection after 20 sec

you can change it to 5 sec, so it will be faster.

https://livecli.github.io/cli.html#cmdoption-http-timeout
