### ISSUE TITLE
Plugin Request - winktv.co.kr

### ISSUE THREAD

**Issue by longsack** [livecli/livecli#36]
PLUGIN REQUEST:
http://winktv.co.kr

You will require a username/password to access the site (it's free) but can only be signed up by Korean's.
--- I will send you my username/password.

I'm able to download live streams via a paid windows software.  I will provide more info if needed, however I do not have much of an idea how to gather info you need.

Thanks

**Comment by back-to** [comment]
A login is not necessary for most of the streams.

**Fan club** streams won't work and sometimes some **random stream** won't work,
maybe they work only with a login.

maybe you can see the differents between the random not working streams.

only tested with streams from `http://www.winktv.co.kr/player/index`
with an url like `http://www.winktv.co.kr/player/previewNew?...`

---

you can test a half working plugin

download the `.py` file from

https://gist.github.com/back-to/e6f5a4dd6b3b8845e984454d140a7368

and sideload it

https://livecli.github.io/latest/cli.html#sideloading-plugins

**Comment by longsack** [comment]
After logging in... here is what I get for every one I try... 

root@ns392703:/# livecli http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201&param[bidx]=2358282&param[ct]=etc
[1] 1806
[2] 1807
root@ns392703:/# http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201&param[bidx]=2358282&param[ct]=etc 1
[3] 1885
[4] 1886
-bash: http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201: No such file or directory
-bash: 1: command not found
[2]   Done                    param[bidx]=2358282
[3]-  Exit 127                http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201
[4]+  Done                    param[bidx]=2358282
root@ns392703:/# [cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201 (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201)

[1]+  Exit 1                  livecli http://www.winktv.co.kr/player/detailNew?param[mc]=qaz0131_2358282_20180526001201
root@ns392703:/# livecli http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446&param[bidx]=2172151&param[ct]=etc
[1] 2608
[2] 2609
root@ns392703:/# 2
-bash: 2: command not found
[2]+  Done                    param[bidx]=2172151
root@ns392703:/# http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446&param[bidx]=2172151&param[ct]=etc
[2] 2671
[3] 2672
root@ns392703:/# -bash: http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446: No such file or directory
1
-bash: 1: command not found
[2]-  Exit 127                http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446
[3]+  Done                    param[bidx]=2172151
root@ns392703:/# livecli http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446&param[bidx]=2172151&param[ct]=etc 1
[2] 2778
[3] 2779
-bash: 1: command not found
root@ns392703:/# [cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446 (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446)
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446 (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446)

[1]   Exit 1                  livecli http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446
[2]-  Exit 1                  livecli http://www.winktv.co.kr/player/detailNew?param[mc]=zhddl486_2172151_20180525232446
[3]+  Done                    param[bidx]=2172151
root@ns392703:/# livecli http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918&param[bidx]=1481438&param[ct]=etc
[1] 3204
[2] 3205
root@ns392703:/# 1
-bash: 1: command not found
[2]+  Done                    param[bidx]=1481438
root@ns392703:/# livecli http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918&param[bidx]=1481438&param[ct]=etc 1
[2] 3384
[3] 3385
-bash: 1: command not found
[3]+  Done                    param[bidx]=1481438
root@ns392703:/# [cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918 (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918)
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918 (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918)
1
-bash: 1: command not found
[1]-  Exit 1                  livecli http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918
[2]+  Exit 1                  livecli http://www.winktv.co.kr/player/detailNew?param[mc]=ekqls070_1481438_20180525161918
root@ns392703:/# 2
-bash: 2: command not found
root@ns392703:/# exit
logout

**Comment by back-to** [comment]
use `"`

like `livecli "URL" best`

the `?` and `&` breaks the terminal

**Comment by longsack** [comment]
Awesome will give it a try... :)

**Comment by longsack** [comment]
Still no good for me anyways python3.6, debian... 

root@ns392703:/var/www/clients/client1/web1/web# livecli "http://www.winktv.co.kr/player/detailNew?param[mc]=ssckmy99_2870290_20180526210112&param[bidx]=2870290&param[ct]=etc" best
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=ssckmy99_2870290_20180526210112&param[bidx]=2870290&param[ct]=etc
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=ssckmy99_2870290_20180526210112&param[bidx]=2870290&param[ct]=etc (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=ssckmy99_2870290_20180526210112&param[bidx]=2870290&param[ct]=etc)
root@ns392703:/var/www/clients/client1/web1/web# livecli "http://www.winktv.co.kr/player/detailNew?param[mc]=sin6678_1489081_20180527003436&param[bidx]=1489081&param[ct]=etc" best
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/detailNew?param[mc]=sin6678_1489081_20180527003436&param[bidx]=1489081&param[ct]=etc
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/detailNew?param[mc]=sin6678_1489081_20180527003436&param[bidx]=1489081&param[ct]=etc (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/detailNew?param[mc]=sin6678_1489081_20180527003436&param[bidx]=1489081&param[ct]=etc)
root@ns392703:/var/www/clients/client1/web1/web# livecli "http://www.winktv.co.kr/player/previewNew?param[mc]=wcommunity_111206_20180526210524&param[bidx]=111206&param[ct]=music" best
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/previewNew?param[mc]=wcommunity_111206_20180526210524&param[bidx]=111206&param[ct]=music
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/previewNew?param[mc]=wcommunity_111206_20180526210524&param[bidx]=111206&param[ct]=music (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/previewNew?param[mc]=wcommunity_111206_20180526210524&param[bidx]=111206&param[ct]=music)
root@ns392703:/var/www/clients/client1/web1/web# livecli "http://www.winktv.co.kr/player/previewNew?param[mc]=ftdltkr61_3030766_20180527005442&param[bidx]=3030766&param[ct]=eat" best
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/previewNew?param[mc]=ftdltkr61_3030766_20180527005442&param[bidx]=3030766&param[ct]=eat
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/previewNew?param[mc]=ftdltkr61_3030766_20180527005442&param[bidx]=3030766&param[ct]=eat (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/previewNew?param[mc]=ftdltkr61_3030766_20180527005442&param[bidx]=3030766&param[ct]=eat)
root@ns392703:/var/www/clients/client1/web1/web# livecli "http://www.winktv.co.kr/player/previewNew?param[mc]=jacica_1267826_20180527002359&param[bidx]=1267826&param[ct]=etc" best
[cli][info] livecli is running as root! Be careful!
[cli][info] Found matching plugin winktv for URL http://www.winktv.co.kr/player/previewNew?param[mc]=jacica_1267826_20180527002359&param[bidx]=1267826&param[ct]=etc
[plugin.winktv][info] This is an experimental plugin.
error: Unable to open URL: http://www.winktv.co.kr/player/previewNew?param[mc]=jacica_1267826_20180527002359&param[bidx]=1267826&param[ct]=etc (400 Client Error: Bad Request for url: http://www.winktv.co.kr/player/previewNew?param[mc]=jacica_1267826_20180527002359&param[bidx]=1267826&param[ct]=etc)

**Comment by longsack** [comment]
Okay..  I was able to test it... 

Just like you I can access some but not all.  The issue is that some videos require the user to login.  I can supply my username/password to the site so that a solution can be found.  Please let me know how to send the info to you for testing.

**Comment by back-to** [comment]
**I don't have an interest in supporting authentication for this website**

---

you can try to use cookies https://livecli.github.io/cli.html#cmdoption-http-cookie it might work
