### ISSUE TITLE
Plugin Request - sakuralive.com

### ISSUE THREAD

**Issue by longsack** [livecli/livecli#37]
PLUGIN REQUEST:
http://www.sakuralive.com

I'm able to download live streams via a paid windows software.  I will provide more info if needed, however I do not have much of an idea how to gather info you need.

Thanks

**Comment by johnthecracker** [comment]
It looks like that rtmp protocol is still popular in Asia.

This is rtmp stream and you have to use rtmp tools like rtmpdumphelper to collect parameters.

To learn more about this type of streaming the best place on planet is stream-recorder.com/forum/

That forum was owned by Applian ages ago and today is run by who knows who and it is down every second day.

So you have to be patient for forum to show up and do some reading there.

Rtmpsuck creates Command.txt file and your best parameters will be found there.

[url=https://postimg.cc/image/3zf87vzvb/][img]https://s31.postimg.cc/3zf87vzvb/Screen_Shot.jpg[/img][/url]

**Comment by back-to** [comment]
It will probably work with a _RTMPStream_,
but are there even real **FREE** streams that are not switched into **PAID** after some minutes?

I don't really have an interest in supporting **PAID** channels.

**Comment by back-to** [comment]
Added it in https://github.com/livecli/livecli/commit/f3ed2526623719400402f7598f3809343d53c378 only **FREE** content is supported.
