### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by thawtes** [livecli/livecli#7]
hello, @back-to 

please adding plugin for izletv.us

sample live channel url : www.izletv.us/trt1-izle

thank you

**Comment by back-to** [comment]
I only add plugins from an **official website or authored third party**
your url is not one of them.

---

For **TRT1** the official website is https://www.trt1.com.tr/canli-izle

There is no point in creating a plugin for this website,
beause they got a **static url** and it changes very rarely

`https://trtcanlitv-lh.akamaihd.net/i/TRT1HD_1@181842/master.m3u8`

**Comment by thawtes** [comment]
yes i know but this is just an example.
pls look
https://www.izletv.us/p4
https://www.izletv.us/p5
the channels there are not everywhere and the special channels
so i made a request ok ?

thank you
