### ISSUE TITLE
tvizle

### ISSUE THREAD

**Issue by thawtes** [livecli/livecli#8]
> I only add plugins from an official website or authored third party
your url is not one of them.
For TRT1 the official website is https://www.trt1.com.tr/canli-izle
There is no point in creating a plugin for this website,
beause they got a static url and it changes very rarely
https://trtcanlitv-lh.akamaihd.net/i/TRT1HD_1@181842/master.m3u8

yes i know but this is just an example.
please, look and check below adress
https://www.izletv.us/p4
https://www.izletv.us/p5
https://www.izletv.us/p3
the channels there are not everywhere and the special channels
sample https://www.izletv.us/sinematv-11-izle

thank you in advance @back-to

**Comment by back-to** [comment]
you are even quoting my reply,
but did you read it?

Livecli **won't** add any Plugin from an **illegal website**,
only from an **official website** or authored third party

**If you want a Plugin find the official website.**
